<?xml version="1.0" encoding="utf-8"?><Database Name="Demo" Class="DemoLinQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-U0ORHBD\SQLEXPRESS;Initial Catalog=Demo;Integrated Security=True" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="DemoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Name" Member="Names">
    <Type Name="Name">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Member="Name1" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>