#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYNHAHANG")]
	public partial class QuanLyNhaHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDETAIL_ORDER(DETAIL_ORDER instance);
    partial void UpdateDETAIL_ORDER(DETAIL_ORDER instance);
    partial void DeleteDETAIL_ORDER(DETAIL_ORDER instance);
    partial void InsertDRINK(DRINK instance);
    partial void UpdateDRINK(DRINK instance);
    partial void DeleteDRINK(DRINK instance);
    partial void InsertFOOD_RESOURCE(FOOD_RESOURCE instance);
    partial void UpdateFOOD_RESOURCE(FOOD_RESOURCE instance);
    partial void DeleteFOOD_RESOURCE(FOOD_RESOURCE instance);
    partial void InsertFOOD_TYPE(FOOD_TYPE instance);
    partial void UpdateFOOD_TYPE(FOOD_TYPE instance);
    partial void DeleteFOOD_TYPE(FOOD_TYPE instance);
    partial void InsertMENU(MENU instance);
    partial void UpdateMENU(MENU instance);
    partial void DeleteMENU(MENU instance);
    partial void InsertORDER(ORDER instance);
    partial void UpdateORDER(ORDER instance);
    partial void DeleteORDER(ORDER instance);
    partial void InsertPERMISSION(PERMISSION instance);
    partial void UpdatePERMISSION(PERMISSION instance);
    partial void DeletePERMISSION(PERMISSION instance);
    partial void InsertRESERVATION(RESERVATION instance);
    partial void UpdateRESERVATION(RESERVATION instance);
    partial void DeleteRESERVATION(RESERVATION instance);
    partial void InsertTABLE(TABLE instance);
    partial void UpdateTABLE(TABLE instance);
    partial void DeleteTABLE(TABLE instance);
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    partial void InsertFOOD(FOOD instance);
    partial void UpdateFOOD(FOOD instance);
    partial void DeleteFOOD(FOOD instance);
    partial void InsertFOOD_RESOURCE_MATERIAL(FOOD_RESOURCE_MATERIAL instance);
    partial void UpdateFOOD_RESOURCE_MATERIAL(FOOD_RESOURCE_MATERIAL instance);
    partial void DeleteFOOD_RESOURCE_MATERIAL(FOOD_RESOURCE_MATERIAL instance);
    #endregion
		
		public QuanLyNhaHangDataContext() : 
				base(global::DAO.Properties.Settings.Default.QUANLYNHAHANGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DETAIL_ORDER> DETAIL_ORDERs
		{
			get
			{
				return this.GetTable<DETAIL_ORDER>();
			}
		}
		
		public System.Data.Linq.Table<DRINK> DRINKs
		{
			get
			{
				return this.GetTable<DRINK>();
			}
		}
		
		public System.Data.Linq.Table<FOOD_RESOURCE> FOOD_RESOURCEs
		{
			get
			{
				return this.GetTable<FOOD_RESOURCE>();
			}
		}
		
		public System.Data.Linq.Table<FOOD_TYPE> FOOD_TYPEs
		{
			get
			{
				return this.GetTable<FOOD_TYPE>();
			}
		}
		
		public System.Data.Linq.Table<MENU> MENUs
		{
			get
			{
				return this.GetTable<MENU>();
			}
		}
		
		public System.Data.Linq.Table<ORDER> ORDERs
		{
			get
			{
				return this.GetTable<ORDER>();
			}
		}
		
		public System.Data.Linq.Table<PERMISSION> PERMISSIONs
		{
			get
			{
				return this.GetTable<PERMISSION>();
			}
		}
		
		public System.Data.Linq.Table<RESERVATION> RESERVATIONs
		{
			get
			{
				return this.GetTable<RESERVATION>();
			}
		}
		
		public System.Data.Linq.Table<TABLE> TABLEs
		{
			get
			{
				return this.GetTable<TABLE>();
			}
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
		
		public System.Data.Linq.Table<FOOD> FOODs
		{
			get
			{
				return this.GetTable<FOOD>();
			}
		}
		
		public System.Data.Linq.Table<FOOD_RESOURCE_MATERIAL> FOOD_RESOURCE_MATERIALs
		{
			get
			{
				return this.GetTable<FOOD_RESOURCE_MATERIAL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DETAIL_ORDER")]
	public partial class DETAIL_ORDER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_ORDER;
		
		private System.Nullable<int> _ID_FOOD;
		
		private string _FOOD_NAME;
		
		private System.Nullable<int> _AMOUNT_OF_FOOD;
		
		private System.Nullable<int> _ID_DRINK;
		
		private string _DRINK_NAME;
		
		private System.Nullable<int> _AMOUNT_OF_DRINK;
		
		private System.Nullable<double> _MONEY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_ORDERChanging(System.Nullable<int> value);
    partial void OnID_ORDERChanged();
    partial void OnID_FOODChanging(System.Nullable<int> value);
    partial void OnID_FOODChanged();
    partial void OnFOOD_NAMEChanging(string value);
    partial void OnFOOD_NAMEChanged();
    partial void OnAMOUNT_OF_FOODChanging(System.Nullable<int> value);
    partial void OnAMOUNT_OF_FOODChanged();
    partial void OnID_DRINKChanging(System.Nullable<int> value);
    partial void OnID_DRINKChanged();
    partial void OnDRINK_NAMEChanging(string value);
    partial void OnDRINK_NAMEChanged();
    partial void OnAMOUNT_OF_DRINKChanging(System.Nullable<int> value);
    partial void OnAMOUNT_OF_DRINKChanged();
    partial void OnMONEYChanging(System.Nullable<double> value);
    partial void OnMONEYChanged();
    #endregion
		
		public DETAIL_ORDER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ORDER", DbType="Int")]
		public System.Nullable<int> ID_ORDER
		{
			get
			{
				return this._ID_ORDER;
			}
			set
			{
				if ((this._ID_ORDER != value))
				{
					this.OnID_ORDERChanging(value);
					this.SendPropertyChanging();
					this._ID_ORDER = value;
					this.SendPropertyChanged("ID_ORDER");
					this.OnID_ORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FOOD", DbType="Int")]
		public System.Nullable<int> ID_FOOD
		{
			get
			{
				return this._ID_FOOD;
			}
			set
			{
				if ((this._ID_FOOD != value))
				{
					this.OnID_FOODChanging(value);
					this.SendPropertyChanging();
					this._ID_FOOD = value;
					this.SendPropertyChanged("ID_FOOD");
					this.OnID_FOODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOOD_NAME", DbType="NVarChar(250)")]
		public string FOOD_NAME
		{
			get
			{
				return this._FOOD_NAME;
			}
			set
			{
				if ((this._FOOD_NAME != value))
				{
					this.OnFOOD_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FOOD_NAME = value;
					this.SendPropertyChanged("FOOD_NAME");
					this.OnFOOD_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT_OF_FOOD", DbType="Int")]
		public System.Nullable<int> AMOUNT_OF_FOOD
		{
			get
			{
				return this._AMOUNT_OF_FOOD;
			}
			set
			{
				if ((this._AMOUNT_OF_FOOD != value))
				{
					this.OnAMOUNT_OF_FOODChanging(value);
					this.SendPropertyChanging();
					this._AMOUNT_OF_FOOD = value;
					this.SendPropertyChanged("AMOUNT_OF_FOOD");
					this.OnAMOUNT_OF_FOODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DRINK", DbType="Int")]
		public System.Nullable<int> ID_DRINK
		{
			get
			{
				return this._ID_DRINK;
			}
			set
			{
				if ((this._ID_DRINK != value))
				{
					this.OnID_DRINKChanging(value);
					this.SendPropertyChanging();
					this._ID_DRINK = value;
					this.SendPropertyChanged("ID_DRINK");
					this.OnID_DRINKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRINK_NAME", DbType="NVarChar(250)")]
		public string DRINK_NAME
		{
			get
			{
				return this._DRINK_NAME;
			}
			set
			{
				if ((this._DRINK_NAME != value))
				{
					this.OnDRINK_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DRINK_NAME = value;
					this.SendPropertyChanged("DRINK_NAME");
					this.OnDRINK_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT_OF_DRINK", DbType="Int")]
		public System.Nullable<int> AMOUNT_OF_DRINK
		{
			get
			{
				return this._AMOUNT_OF_DRINK;
			}
			set
			{
				if ((this._AMOUNT_OF_DRINK != value))
				{
					this.OnAMOUNT_OF_DRINKChanging(value);
					this.SendPropertyChanging();
					this._AMOUNT_OF_DRINK = value;
					this.SendPropertyChanged("AMOUNT_OF_DRINK");
					this.OnAMOUNT_OF_DRINKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONEY", DbType="Float")]
		public System.Nullable<double> MONEY
		{
			get
			{
				return this._MONEY;
			}
			set
			{
				if ((this._MONEY != value))
				{
					this.OnMONEYChanging(value);
					this.SendPropertyChanging();
					this._MONEY = value;
					this.SendPropertyChanged("MONEY");
					this.OnMONEYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DRINK")]
	public partial class DRINK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DRINK_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDRINK_NAMEChanging(string value);
    partial void OnDRINK_NAMEChanged();
    #endregion
		
		public DRINK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRINK_NAME", DbType="NVarChar(250)")]
		public string DRINK_NAME
		{
			get
			{
				return this._DRINK_NAME;
			}
			set
			{
				if ((this._DRINK_NAME != value))
				{
					this.OnDRINK_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DRINK_NAME = value;
					this.SendPropertyChanged("DRINK_NAME");
					this.OnDRINK_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FOOD_RESOURCE")]
	public partial class FOOD_RESOURCE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RESOURCE_NAME;
		
		private System.Nullable<int> _AMOUNT;
		
		private System.Nullable<double> _MONEY;
		
		private System.Nullable<double> _TOTAL_MONEY;
		
		private System.Nullable<System.DateTime> _DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRESOURCE_NAMEChanging(string value);
    partial void OnRESOURCE_NAMEChanged();
    partial void OnAMOUNTChanging(System.Nullable<int> value);
    partial void OnAMOUNTChanged();
    partial void OnMONEYChanging(System.Nullable<double> value);
    partial void OnMONEYChanged();
    partial void OnTOTAL_MONEYChanging(System.Nullable<double> value);
    partial void OnTOTAL_MONEYChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    #endregion
		
		public FOOD_RESOURCE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESOURCE_NAME", DbType="NVarChar(250)")]
		public string RESOURCE_NAME
		{
			get
			{
				return this._RESOURCE_NAME;
			}
			set
			{
				if ((this._RESOURCE_NAME != value))
				{
					this.OnRESOURCE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._RESOURCE_NAME = value;
					this.SendPropertyChanged("RESOURCE_NAME");
					this.OnRESOURCE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT", DbType="Int")]
		public System.Nullable<int> AMOUNT
		{
			get
			{
				return this._AMOUNT;
			}
			set
			{
				if ((this._AMOUNT != value))
				{
					this.OnAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._AMOUNT = value;
					this.SendPropertyChanged("AMOUNT");
					this.OnAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONEY", DbType="Float")]
		public System.Nullable<double> MONEY
		{
			get
			{
				return this._MONEY;
			}
			set
			{
				if ((this._MONEY != value))
				{
					this.OnMONEYChanging(value);
					this.SendPropertyChanging();
					this._MONEY = value;
					this.SendPropertyChanged("MONEY");
					this.OnMONEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_MONEY", DbType="Float")]
		public System.Nullable<double> TOTAL_MONEY
		{
			get
			{
				return this._TOTAL_MONEY;
			}
			set
			{
				if ((this._TOTAL_MONEY != value))
				{
					this.OnTOTAL_MONEYChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_MONEY = value;
					this.SendPropertyChanged("TOTAL_MONEY");
					this.OnTOTAL_MONEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FOOD_TYPE")]
	public partial class FOOD_TYPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FOOD_TYPE1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFOOD_TYPE1Changing(string value);
    partial void OnFOOD_TYPE1Changed();
    #endregion
		
		public FOOD_TYPE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="FOOD_TYPE", Storage="_FOOD_TYPE1", DbType="NVarChar(250)")]
		public string FOOD_TYPE1
		{
			get
			{
				return this._FOOD_TYPE1;
			}
			set
			{
				if ((this._FOOD_TYPE1 != value))
				{
					this.OnFOOD_TYPE1Changing(value);
					this.SendPropertyChanging();
					this._FOOD_TYPE1 = value;
					this.SendPropertyChanged("FOOD_TYPE1");
					this.OnFOOD_TYPE1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MENU")]
	public partial class MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _WEEK_DAY;
		
		private System.Nullable<int> _ID_FOOD;
		
		private string _FOOD_NAME;
		
		private System.Nullable<int> _ID_DRINK;
		
		private string _DRINK_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnWEEK_DAYChanging(System.Nullable<int> value);
    partial void OnWEEK_DAYChanged();
    partial void OnID_FOODChanging(System.Nullable<int> value);
    partial void OnID_FOODChanged();
    partial void OnFOOD_NAMEChanging(string value);
    partial void OnFOOD_NAMEChanged();
    partial void OnID_DRINKChanging(System.Nullable<int> value);
    partial void OnID_DRINKChanged();
    partial void OnDRINK_NAMEChanging(string value);
    partial void OnDRINK_NAMEChanged();
    #endregion
		
		public MENU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEEK_DAY", DbType="Int")]
		public System.Nullable<int> WEEK_DAY
		{
			get
			{
				return this._WEEK_DAY;
			}
			set
			{
				if ((this._WEEK_DAY != value))
				{
					this.OnWEEK_DAYChanging(value);
					this.SendPropertyChanging();
					this._WEEK_DAY = value;
					this.SendPropertyChanged("WEEK_DAY");
					this.OnWEEK_DAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FOOD", DbType="Int")]
		public System.Nullable<int> ID_FOOD
		{
			get
			{
				return this._ID_FOOD;
			}
			set
			{
				if ((this._ID_FOOD != value))
				{
					this.OnID_FOODChanging(value);
					this.SendPropertyChanging();
					this._ID_FOOD = value;
					this.SendPropertyChanged("ID_FOOD");
					this.OnID_FOODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOOD_NAME", DbType="NVarChar(250)")]
		public string FOOD_NAME
		{
			get
			{
				return this._FOOD_NAME;
			}
			set
			{
				if ((this._FOOD_NAME != value))
				{
					this.OnFOOD_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FOOD_NAME = value;
					this.SendPropertyChanged("FOOD_NAME");
					this.OnFOOD_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DRINK", DbType="Int")]
		public System.Nullable<int> ID_DRINK
		{
			get
			{
				return this._ID_DRINK;
			}
			set
			{
				if ((this._ID_DRINK != value))
				{
					this.OnID_DRINKChanging(value);
					this.SendPropertyChanging();
					this._ID_DRINK = value;
					this.SendPropertyChanged("ID_DRINK");
					this.OnID_DRINKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRINK_NAME", DbType="NVarChar(250)")]
		public string DRINK_NAME
		{
			get
			{
				return this._DRINK_NAME;
			}
			set
			{
				if ((this._DRINK_NAME != value))
				{
					this.OnDRINK_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DRINK_NAME = value;
					this.SendPropertyChanged("DRINK_NAME");
					this.OnDRINK_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[ORDER]")]
	public partial class ORDER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_USER;
		
		private System.Nullable<int> _ID_TABLE;
		
		private System.Nullable<double> _TOTAL_MONEY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_USERChanging(System.Nullable<int> value);
    partial void OnID_USERChanged();
    partial void OnID_TABLEChanging(System.Nullable<int> value);
    partial void OnID_TABLEChanged();
    partial void OnTOTAL_MONEYChanging(System.Nullable<double> value);
    partial void OnTOTAL_MONEYChanged();
    #endregion
		
		public ORDER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int")]
		public System.Nullable<int> ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this.OnID_USERChanging(value);
					this.SendPropertyChanging();
					this._ID_USER = value;
					this.SendPropertyChanged("ID_USER");
					this.OnID_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TABLE", DbType="Int")]
		public System.Nullable<int> ID_TABLE
		{
			get
			{
				return this._ID_TABLE;
			}
			set
			{
				if ((this._ID_TABLE != value))
				{
					this.OnID_TABLEChanging(value);
					this.SendPropertyChanging();
					this._ID_TABLE = value;
					this.SendPropertyChanged("ID_TABLE");
					this.OnID_TABLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_MONEY", DbType="Float")]
		public System.Nullable<double> TOTAL_MONEY
		{
			get
			{
				return this._TOTAL_MONEY;
			}
			set
			{
				if ((this._TOTAL_MONEY != value))
				{
					this.OnTOTAL_MONEYChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_MONEY = value;
					this.SendPropertyChanged("TOTAL_MONEY");
					this.OnTOTAL_MONEYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PERMISSION")]
	public partial class PERMISSION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ROLE_TYPE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnROLE_TYPEChanging(string value);
    partial void OnROLE_TYPEChanged();
    #endregion
		
		public PERMISSION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_TYPE", DbType="NVarChar(50)")]
		public string ROLE_TYPE
		{
			get
			{
				return this._ROLE_TYPE;
			}
			set
			{
				if ((this._ROLE_TYPE != value))
				{
					this.OnROLE_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ROLE_TYPE = value;
					this.SendPropertyChanged("ROLE_TYPE");
					this.OnROLE_TYPEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RESERVATION")]
	public partial class RESERVATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CUSTOMER_NAME;
		
		private string _PHONE;
		
		private System.Nullable<int> _ID_TABLE;
		
		private System.Nullable<int> _STATUS;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private System.Nullable<System.TimeSpan> _TIME;
		
		private System.Nullable<int> _ID_USER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCUSTOMER_NAMEChanging(string value);
    partial void OnCUSTOMER_NAMEChanged();
    partial void OnPHONEChanging(string value);
    partial void OnPHONEChanged();
    partial void OnID_TABLEChanging(System.Nullable<int> value);
    partial void OnID_TABLEChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnTIMEChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTIMEChanged();
    partial void OnID_USERChanging(System.Nullable<int> value);
    partial void OnID_USERChanged();
    #endregion
		
		public RESERVATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="NVarChar(250)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this.OnCUSTOMER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_NAME = value;
					this.SendPropertyChanged("CUSTOMER_NAME");
					this.OnCUSTOMER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="NChar(11)")]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this.OnPHONEChanging(value);
					this.SendPropertyChanging();
					this._PHONE = value;
					this.SendPropertyChanged("PHONE");
					this.OnPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TABLE", DbType="Int")]
		public System.Nullable<int> ID_TABLE
		{
			get
			{
				return this._ID_TABLE;
			}
			set
			{
				if ((this._ID_TABLE != value))
				{
					this.OnID_TABLEChanging(value);
					this.SendPropertyChanging();
					this._ID_TABLE = value;
					this.SendPropertyChanged("ID_TABLE");
					this.OnID_TABLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME", DbType="Time")]
		public System.Nullable<System.TimeSpan> TIME
		{
			get
			{
				return this._TIME;
			}
			set
			{
				if ((this._TIME != value))
				{
					this.OnTIMEChanging(value);
					this.SendPropertyChanging();
					this._TIME = value;
					this.SendPropertyChanged("TIME");
					this.OnTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int")]
		public System.Nullable<int> ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this.OnID_USERChanging(value);
					this.SendPropertyChanging();
					this._ID_USER = value;
					this.SendPropertyChanged("ID_USER");
					this.OnID_USERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[TABLE]")]
	public partial class TABLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _TABLE_NAME;
		
		private System.Nullable<int> _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTABLE_NAMEChanging(System.Nullable<int> value);
    partial void OnTABLE_NAMEChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    #endregion
		
		public TABLE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_NAME", DbType="Int")]
		public System.Nullable<int> TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this.OnTABLE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._TABLE_NAME = value;
					this.SendPropertyChanged("TABLE_NAME");
					this.OnTABLE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[USER]")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FULL_NAME;
		
		private string _GENDER;
		
		private string _ADDRESS;
		
		private int _ROLE;
		
		private string _USER_NAME;
		
		private string _PASSWORD;
		
		private System.Nullable<int> _REMEMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFULL_NAMEChanging(string value);
    partial void OnFULL_NAMEChanged();
    partial void OnGENDERChanging(string value);
    partial void OnGENDERChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnROLEChanging(int value);
    partial void OnROLEChanged();
    partial void OnUSER_NAMEChanging(string value);
    partial void OnUSER_NAMEChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnREMEMBERChanging(System.Nullable<int> value);
    partial void OnREMEMBERChanged();
    #endregion
		
		public USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULL_NAME", DbType="NVarChar(100)")]
		public string FULL_NAME
		{
			get
			{
				return this._FULL_NAME;
			}
			set
			{
				if ((this._FULL_NAME != value))
				{
					this.OnFULL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FULL_NAME = value;
					this.SendPropertyChanged("FULL_NAME");
					this.OnFULL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="NVarChar(20)")]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this.OnGENDERChanging(value);
					this.SendPropertyChanging();
					this._GENDER = value;
					this.SendPropertyChanged("GENDER");
					this.OnGENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(250)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE", DbType="Int NOT NULL")]
		public int ROLE
		{
			get
			{
				return this._ROLE;
			}
			set
			{
				if ((this._ROLE != value))
				{
					this.OnROLEChanging(value);
					this.SendPropertyChanging();
					this._ROLE = value;
					this.SendPropertyChanged("ROLE");
					this.OnROLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this.OnUSER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_NAME = value;
					this.SendPropertyChanged("USER_NAME");
					this.OnUSER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMEMBER", DbType="Int")]
		public System.Nullable<int> REMEMBER
		{
			get
			{
				return this._REMEMBER;
			}
			set
			{
				if ((this._REMEMBER != value))
				{
					this.OnREMEMBERChanging(value);
					this.SendPropertyChanging();
					this._REMEMBER = value;
					this.SendPropertyChanged("REMEMBER");
					this.OnREMEMBERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FOOD")]
	public partial class FOOD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FOOD_NAME;
		
		private string _FOOD_TYPE;
		
		private System.Nullable<int> _ID_FOOD_TYPE;
		
		private string _FOOD_DESCRIPTION;
		
		private System.Nullable<double> _PRICE;
		
		private System.Nullable<bool> _AVAIABLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFOOD_NAMEChanging(string value);
    partial void OnFOOD_NAMEChanged();
    partial void OnFOOD_TYPEChanging(string value);
    partial void OnFOOD_TYPEChanged();
    partial void OnID_FOOD_TYPEChanging(System.Nullable<int> value);
    partial void OnID_FOOD_TYPEChanged();
    partial void OnFOOD_DESCRIPTIONChanging(string value);
    partial void OnFOOD_DESCRIPTIONChanged();
    partial void OnPRICEChanging(System.Nullable<double> value);
    partial void OnPRICEChanged();
    partial void OnAVAIABLEChanging(System.Nullable<bool> value);
    partial void OnAVAIABLEChanged();
    #endregion
		
		public FOOD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOOD_NAME", DbType="NVarChar(250)")]
		public string FOOD_NAME
		{
			get
			{
				return this._FOOD_NAME;
			}
			set
			{
				if ((this._FOOD_NAME != value))
				{
					this.OnFOOD_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FOOD_NAME = value;
					this.SendPropertyChanged("FOOD_NAME");
					this.OnFOOD_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOOD_TYPE", DbType="NVarChar(250)")]
		public string FOOD_TYPE
		{
			get
			{
				return this._FOOD_TYPE;
			}
			set
			{
				if ((this._FOOD_TYPE != value))
				{
					this.OnFOOD_TYPEChanging(value);
					this.SendPropertyChanging();
					this._FOOD_TYPE = value;
					this.SendPropertyChanged("FOOD_TYPE");
					this.OnFOOD_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FOOD_TYPE", DbType="Int")]
		public System.Nullable<int> ID_FOOD_TYPE
		{
			get
			{
				return this._ID_FOOD_TYPE;
			}
			set
			{
				if ((this._ID_FOOD_TYPE != value))
				{
					this.OnID_FOOD_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ID_FOOD_TYPE = value;
					this.SendPropertyChanged("ID_FOOD_TYPE");
					this.OnID_FOOD_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOOD_DESCRIPTION", DbType="NVarChar(200)")]
		public string FOOD_DESCRIPTION
		{
			get
			{
				return this._FOOD_DESCRIPTION;
			}
			set
			{
				if ((this._FOOD_DESCRIPTION != value))
				{
					this.OnFOOD_DESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._FOOD_DESCRIPTION = value;
					this.SendPropertyChanged("FOOD_DESCRIPTION");
					this.OnFOOD_DESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Float")]
		public System.Nullable<double> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVAIABLE", DbType="Bit")]
		public System.Nullable<bool> AVAIABLE
		{
			get
			{
				return this._AVAIABLE;
			}
			set
			{
				if ((this._AVAIABLE != value))
				{
					this.OnAVAIABLEChanging(value);
					this.SendPropertyChanging();
					this._AVAIABLE = value;
					this.SendPropertyChanged("AVAIABLE");
					this.OnAVAIABLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FOOD_RESOURCE_MATERIAL")]
	public partial class FOOD_RESOURCE_MATERIAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_FOOD;
		
		private long _ID_RESOURCE;
		
		private string _NOTE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_FOODChanging(long value);
    partial void OnID_FOODChanged();
    partial void OnID_RESOURCEChanging(long value);
    partial void OnID_RESOURCEChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    #endregion
		
		public FOOD_RESOURCE_MATERIAL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FOOD", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID_FOOD
		{
			get
			{
				return this._ID_FOOD;
			}
			set
			{
				if ((this._ID_FOOD != value))
				{
					this.OnID_FOODChanging(value);
					this.SendPropertyChanging();
					this._ID_FOOD = value;
					this.SendPropertyChanged("ID_FOOD");
					this.OnID_FOODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RESOURCE", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID_RESOURCE
		{
			get
			{
				return this._ID_RESOURCE;
			}
			set
			{
				if ((this._ID_RESOURCE != value))
				{
					this.OnID_RESOURCEChanging(value);
					this.SendPropertyChanging();
					this._ID_RESOURCE = value;
					this.SendPropertyChanged("ID_RESOURCE");
					this.OnID_RESOURCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NChar(100)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
