<?xml version="1.0" encoding="utf-8"?><Database Name="QUANLYNHAHANG" Class="QuanLyNhaHangDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-U0ORHBD\SQLEXPRESS;Initial Catalog=QUANLYNHAHANG;Integrated Security=True" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="QUANLYNHAHANGConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DETAIL_ORDER" Member="DETAIL_ORDERs">
    <Type Name="DETAIL_ORDER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_ORDER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_FOOD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FOOD_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AMOUNT_OF_FOOD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_DRINK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMOUNT_OF_DRINK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONEY" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DRINK" Member="DRINKs">
    <Type Name="DRINK">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DRINK_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FOOD" Member="FOODs">
    <Type Name="FOOD">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FOOD_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FOOD_TYPE" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ID_FOOD_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FOOD_RESOURCE" Member="FOOD_RESOURCEs">
    <Type Name="FOOD_RESOURCE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RESOURCE_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AMOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONEY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL_MONEY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FOOD_TYPE" Member="FOOD_TYPEs">
    <Type Name="FOOD_TYPE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FOOD_TYPE" Member="FOOD_TYPE1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MENU" Member="MENUs">
    <Type Name="MENU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WEEK_DAY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_FOOD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FOOD_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ID_DRINK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DRINK_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[ORDER]" Member="ORDERs">
    <Type Name="ORDER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_USER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TABLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_MONEY" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PERMISSION" Member="PERMISSIONs">
    <Type Name="PERMISSION">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ROLE_TYPE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RESERVATION" Member="RESERVATIONs">
    <Type Name="RESERVATION">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CUSTOMER_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PHONE" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Column Name="ID_TABLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TIME" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="ID_USER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[TABLE]" Member="TABLEs">
    <Type Name="TABLE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TABLE_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[USER]" Member="USERs">
    <Type Name="USER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FULL_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GENDER" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ROLE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USER_NAME" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="REMEMBER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>